In [1]:
import numpy as np

In [23]:
X = np.random.randn(5,5)

In [24]:
X

array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847,  0.29508534],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063, -0.3992633 ],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528, -0.94237801],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281, -0.54756757],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.37710398]])

In [25]:
np.linalg.det(X)

-4.90126802091542

In [26]:
v = X[-1,:]

In [27]:
v

array([-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.37710398])

In [28]:
X[:,-1] = X[:,-2]

In [29]:
X

array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847, -0.72983847],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063, -0.94060063],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528,  1.62087528],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281,  0.11578281],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  1.16818994]])

In [30]:
np.round(np.linalg.det(X))

-0.0

## Swapping Rows

In [31]:
v = np.random.randn(1,5)

In [32]:
X[:,-1] = v

In [33]:
X

array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847, -0.16140774],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063,  1.07518168],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528, -1.45380214],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281,  0.49610478],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.57131252]])

In [34]:
np.round(np.linalg.det(X))

11.0

In [44]:
X = np.array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847, -0.16140774],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063,  1.07518168],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528, -1.45380214],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281,  0.49610478],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.57131252]])

In [45]:
X

array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847, -0.16140774],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063,  1.07518168],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528, -1.45380214],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281,  0.49610478],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.57131252]])

In [46]:
Y = np.array([[ 0.77358177, -0.35787505,  1.00764839, -0.72983847, -0.16140774],
       [-0.70412617,  0.31064395, -0.10922101, -0.94060063,  1.07518168],
       [ 1.83853557, -1.07213982,  0.09514373,  0.11578281,  0.49610478],
       [ 0.7477844 ,  1.23862846, -0.29087281,  1.62087528, -1.45380214],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  0.57131252]])

In [47]:
np.linalg.det(X)

10.70520139840758

In [48]:
np.linalg.det(Y)

-10.70520139840758

## Shifted Det

In [49]:
XShifted = X + np.eye(5,5)

In [50]:
XShifted

array([[ 1.77358177, -0.35787505,  1.00764839, -0.72983847, -0.16140774],
       [-0.70412617,  1.31064395, -0.10922101, -0.94060063,  1.07518168],
       [ 0.7477844 ,  1.23862846,  0.70912719,  1.62087528, -1.45380214],
       [ 1.83853557, -1.07213982,  0.09514373,  1.11578281,  0.49610478],
       [-0.73354102,  0.6587024 ,  1.12192683,  1.16818994,  1.57131252]])

In [51]:
np.linalg.det(XShifted)

32.887236993457584