In [1]:
import numpy as np


---
# A zoo of matrices
---


In [3]:

# square vs. rectangular
S = np.random.randn(2,3)
R = np.random.randn(4,2) # 4 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(2)
print(I), print(' ')

# zeros
Z = np.zeros((2,2))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 2])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.8835073  -0.55032428 -0.87446234]
 [ 0.10929262  0.0292219  -0.21361503]]
 
[[-0.02116632 -1.29939991]
 [-0.44111398 -1.72680615]
 [ 0.426687   -0.30052262]
 [ 0.35302651 -0.75236581]]
[[1. 0.]
 [0. 1.]]
 
[[0. 0.]
 [0. 0.]]
 
[[1 0 0]
 [0 2 0]
 [0 0 2]]
 
[[ 0.41944223  0.          0.          0.          0.        ]
 [ 0.57420504  0.10117033  0.          0.          0.        ]
 [ 0.72241376  1.21085142 -0.39036424  0.          0.        ]
 [-0.14864975 -0.27817928  0.01535311 -0.48432456  0.        ]
 [-1.23190769 -0.97655346  2.63211287  1.56107672 -1.64649624]]
 
[[ 0.92124626  0.73892963 -0.96787274  0.92670887  0.94928376 -0.68870411]
 [-0.44527428  0.40322884 -0.85947146 -1.37778957  1.41015842 -0.01956967]
 [-0.01151659  0.24272394 -0.62411056  0.45332716 -0.72740215 -0.42098193]]



---
# Matrix addition and subtraction
---


In [4]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
try:
    print(A+B)
except ValueError as e:
    print(e)
print(A+C)



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

operands could not be broadcast together with shapes (5,4) (5,3) 
[[-0.62909766  1.39870856  0.97924664 -0.8952668 ]
 [-0.31643604  1.87465258 -0.74800298 -2.2754109 ]
 [ 0.81801926  0.4261303  -0.86262425  1.02158909]
 [ 0.82566595 -1.13180708  2.51809731  0.15903215]
 [ 0.69079205 -1.57370762 -0.54918671  0.17147195]]
[[ 0.95160011 -0.08933808 -1.13038299  0.25628693 -1.18306615]
 [ 0.87723346 -1.10468928 -2.27687998 -0.23860173 -1.26626386]
 [-1.20206739  0.97458024 -0.90354577 -0.57214778 -0.37167156]
 [-1.56885119 -0.73245294  0.37421977  0.41126744 -0.34523591]
 [-1.03733732  1.61872863 -2.04008781  1.34363696 -1.66045491]]
 
[[ 0.98160011 -0.08933808 -1.13038299  0.25628693 -1.18306615]
 [ 0.87723346 -1.07468928 -2.27687998 -0.23860173 -1.26626386]
 [-1.20206739  0.97458024 -0.87354577 -0.57214778 -0.37167156]
 [-1.56885119 -0.73245294  0.37421977  0.44126744 -0.34523591]
 [-1.03733732  1.61872863 -2.04008781  1.34363696 -1.63045491]]


(None, None, None)


---
# Matrix-scalar multiplication
---


In [5]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# Transpose

In [6]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [8]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# Diagonal and trace
---


In [9]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[-10. -12.  -1.   1.]
 [ -4.  -3.  -6.  -7.]
 [ 12.   3.   1.   1.]
 [ 14.   4. -14.   1.]]
 
[-10.  -3.   1.   1.]
[[-10.   0.   0.   0.]
 [  0.  -3.   0.   0.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
-11.0 -11.0



---
#  Broadcasting matrix arithmetic
---


In [7]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row ;  how you fill up

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ')

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


(None, None)

In [8]:
# broadcast on the rows
print(A+r), print(' ')



[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 


(None, None)

In [10]:
# broadcast on the columns
print(A+c)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [11]:
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
