In [1]:
import numpy as np


---
# A zoo of matrices
---


In [3]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D), print(' ')

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[ 1.58760953  0.95378191 -1.28942953 -1.55834998  0.54403618]
 [ 0.21778712 -0.74133222 -2.26477479 -1.20465488 -0.54465927]
 [-0.33945892 -0.01495321  0.58378704  1.13035237  0.29887429]
 [ 0.51881998  0.84774997  1.2925164   0.13048948  0.97941374]
 [ 1.44186903 -2.07481133  0.41705264 -0.09072609 -0.08189179]]
 
[[-1.22999457  1.84837225]
 [ 1.69376443  0.63711103]
 [ 1.19565806  0.90524223]
 [ 0.07724844  0.69112279]
 [-1.97850822 -0.0593312 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
 
[[ 0.49747394  0.          0.          0.          0.        ]
 [ 1.12875813  0.72594324  0.          0.          0.        ]
 [-1.1474631   1.41789576  1.77106221  0.          0.        ]
 [ 1.75402483  0.31317521  0.6380131   0.3030979   0.        ]
 [-0.82691365 -0.2711439   0.68677357  0.72651399  1.15880153]]
 
[[-0.99105421 -2.14271642  1.01471973  0.70193241  1.91556


---
# Matrix addition and subtraction
---


In [5]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
try:
    print(A+B)
except ValueError as e:
    print(e)
print(A+C)



# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

operands could not be broadcast together with shapes (5,4) (5,3) 
[[ 1.27788739  1.1686461   1.44398754  0.18212083]
 [ 1.69389121  0.0610203  -0.93367236 -0.28545947]
 [ 2.36867024  1.63153697 -1.49347151  1.45568302]
 [ 0.16116835  0.45415088  3.61644081 -1.14515534]
 [ 0.70236188 -0.87405671  0.2247604  -2.75199093]]
[[-1.42319262 -1.2665533   0.00740627 -0.20969971 -1.73514715]
 [ 2.64295016 -0.59811531  0.33816696 -1.69822801 -1.02093228]
 [-0.11694396  0.97664284  0.18063086 -1.55814095  0.31054121]
 [ 0.7065955  -0.66378669  0.03839844 -2.28047612 -0.14415856]
 [ 0.26120901 -1.02721334  1.83932745 -0.53726975  0.60572775]]
 
[[-1.39319262 -1.2665533   0.00740627 -0.20969971 -1.73514715]
 [ 2.64295016 -0.56811531  0.33816696 -1.69822801 -1.02093228]
 [-0.11694396  0.97664284  0.21063086 -1.55814095  0.31054121]
 [ 0.7065955  -0.66378669  0.03839844 -2.25047612 -0.14415856]
 [ 0.26120901 -1.02721334  1.83932745 -0.53726975  0.63572775]]


(None, None, None)


---
# Matrix-scalar multiplication
---


In [6]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


# Transpose

In [7]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [8]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(np.matrix(C).H) # note the sign flips!


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# Diagonal and trace
---


In [9]:

M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[-10. -12.  -1.   1.]
 [ -4.  -3.  -6.  -7.]
 [ 12.   3.   1.   1.]
 [ 14.   4. -14.   1.]]
 
[-10.  -3.   1.   1.]
[[-10.   0.   0.   0.]
 [  0.  -3.   0.   0.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
-11.0 -11.0



---
#  Broadcasting matrix arithmetic
---


In [10]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [11]:
# broadcast on the rows
print(A+r), print(' ')



[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 


(None, None)

In [12]:
# broadcast on the columns
print(A+c)
# print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 