In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# Computing rank: theory and practice
---


In [2]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra))

# set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]

rb = np.linalg.matrix_rank(B)
# print('rank = ' + str(rb))

rank = 4


In [4]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4



---
# Rank of A^TA and AA^T
---


In [5]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3



---
# Making a matrix full-rank by "shifting"
---


In [6]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*A.T@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30


## Check if a vector is in the span of a matrix

In [2]:
# vector
v = np.array([[1,2,3,4]]).T

In [3]:
v

array([[1],
       [2],
       [3],
       [4]])

In [4]:
v.shape

(4, 1)

In [6]:
np.linalg.matrix_rank(v)

1

In [8]:
## Creating the matrices as concatenated vectors ; good for visualization

S = np.vstack(([3,0,4,7],[1,99,67,2])).T
T = np.vstack(([1,2,2,2],[0,0,1,2])).T

In [9]:
S

array([[ 3,  1],
       [ 0, 99],
       [ 4, 67],
       [ 7,  2]])

In [14]:
np.linalg.matrix_rank(S)

2

In [10]:
T

array([[1, 0],
       [2, 0],
       [2, 1],
       [2, 2]])

In [11]:
Sv = np.concatenate((S,v),axis = 1)

In [12]:
Sv

array([[ 3,  1,  1],
       [ 0, 99,  2],
       [ 4, 67,  3],
       [ 7,  2,  4]])

In [13]:
np.linalg.matrix_rank(Sv)  # as rank increased, thus not contained....

3